-- schema.sql
-- DROP TABLE IF EXISTS users;
-- DROP TABLE IF EXISTS books;
-- DROP TABLE IF EXISTS user_account;

CREATE TABLE IF NOT EXISTS users(
  id NUMERIC IDENTITY PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS books(
  id NUMERIC IDENTITY PRIMARY KEY,
  isn VARCHAR(128) NOT NULL UNIQUE,
  author VARCHAR(128) NOT NULL,
  title VARCHAR(128) NOT NULL,
  user_id INTEGER
);

CREATE TABLE IF NOT EXISTS user_account(
  id NUMERIC IDENTITY PRIMARY KEY,
  login VARCHAR(128) NOT NULL,
  password VARCHAR(128) NOT NULL,
  user_id INTEGER UNIQUE
);

ALTER TABLE user_account ADD CONSTRAINT FK_ACCOUNT_USER FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE books ADD CONSTRAINT FK_USER_BOOK FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;